### ISSUE TITLE
程序容易崩溃

### ISSUE THREAD

**Issue by liang-hiwin** [IrineSistiana/mosproxy#6]
添加GODEBUG="asynctimerchan=1"，也没用，一样运行一会就崩溃了。

**Comment by IrineSistiana** [comment]
看下崩溃日志。不好找就搜 "panic"。

**Comment by liang-hiwin** [comment]
> 看下崩溃日志。不好找就搜 "panic"。
我配置下log

**Comment by liang-hiwin** [comment]
> 看下崩溃日志。不好找就搜 "panic"。



> 看下崩溃日志。不好找就搜 "panic"。

```
Sep 17 18:51:11 debian12 mosproxy[1351435]: panic: negative concurrent counter
Sep 17 18:51:11 debian12 mosproxy[1351435]: goroutine 70 [running]:
Sep 17 18:51:11 debian12 mosproxy[1351435]: github.com/IrineSistiana/mosproxy/app/router.(*tcpServer).handleConn.func1.1()
Sep 17 18:51:11 debian12 mosproxy[1351435]:         /root/build/mosproxy-dev/app/router/server_tcp.go:151 +0x3d
Sep 17 18:51:11 debian12 mosproxy[1351435]: github.com/IrineSistiana/mosproxy/app/router.(*tcpServer).handleConn.func1()
Sep 17 18:51:11 debian12 mosproxy[1351435]:         /root/build/mosproxy-dev/app/router/server_tcp.go:155 +0x88
Sep 17 18:51:11 debian12 mosproxy[1351435]: github.com/IrineSistiana/gopool.Go.func1(0xc00013c148?)
Sep 17 18:51:11 debian12 mosproxy[1351435]:         /root/go/pkg/mod/github.com/!irine!sistiana/gopool@v0.0.0-20240118084800-c21759e56cf2/pool.go:12 +0x12
Sep 17 18:51:11 debian12 mosproxy[1351435]: github.com/IrineSistiana/gopool.(*goWorker[...]).jobLoop(0x13b6040)
Sep 17 18:51:11 debian12 mosproxy[1351435]:         /root/go/pkg/mod/github.com/!irine!sistiana/gopool@v0.0.0-20240118084800-c21759e56cf2/pool.go:244 +0x54
Sep 17 18:51:11 debian12 mosproxy[1351435]: created by github.com/IrineSistiana/gopool.(*shard[...]).newWorker in goroutine 49
Sep 17 18:51:11 debian12 mosproxy[1351435]:         /root/go/pkg/mod/github.com/!irine!sistiana/gopool@v0.0.0-20240118084800-c21759e56cf2/pool.go:265 +0xd8
Sep 17 18:51:11 debian12 systemd[1]: mosproxy.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 17 18:51:11 debian12 systemd[1]: mosproxy.service: Failed with result 'exit-code'.
Sep 17 18:51:11 debian12 systemd[1]: mosproxy.service: Consumed 1.767s CPU time.


```

**Comment by IrineSistiana** [comment]
应该可以了 3b6bee28f958318f366d777cca5aa008de95e793
